name: Test automatically set milestone

# This only assigns on newly opened PRs
on:
  pull_request:
    branches: [ "main" ]
    types: [ opened ]

jobs:
  Set-Milestone:
    runs-on: ubuntu-latest
        
    steps:
      - name: Automatically set milestone to PR
        uses: cgetc/automatically-set-milestone-to-issue@v0.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-prefix: ""
