name: Test automatically set milestone on new PRs

# This only assigns on newly opened PRs, but also allows manually running it
on:
  pull_request:
    branches: [ "main" ]
    types: [ opened ]
  workflow_dispatch:
    # no inputs needed here

jobs:
  Set-Milestone:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
        
    steps:
      - name: Automatically set milestone to PR
        uses: cgetc/automatically-set-milestone-to-issue@v0.1.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-prefix: ""
