name: Test automatically set milestone

on:
  issues:
    types: [opened]

jobs:
  Set-Milestone:
    runs-on: ubuntu-latest
        
    steps:
      - name: Automatically set milestone to issue
        uses: cgetc/automatically-set-milestone-to-issue@v0.1.3
        with:
          version-prefix: ""
