name: learn-github-actions-check-bats
run-name: ${{ github.actor }} is learning GitHub Actions (Check BATS version)
#on: [push]
on:
  workflow_dispatch:
    # no inputs
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
