name: Delombok
on:
  workflow_dispatch:
    # no inputs needed here

jobs:
  Run-Delombok:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2        
        
      - name: Run Delombok
        uses: sleberknight/delombok-action@main
        with:
          sourcePath: src  # this is the default...just testing
        
      - name: Print the Delomboked code
        run: find src-delombok -type f -exec cat {} \;
        shell: bash
